# Site settings
title: HAT Barcelona tours
email: info@hatbarcelona.com
locale: en
url: "https://www.hatbarcelona.com" # the base hostname & protocol for your site
exclude: [Gemfile, Gemfile.lock, vendor]

locales:
  en: en_GB
  es: es_ES
  ca: ca_ES

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - uglifier
