# Site settings
title: HAT Barcelona tour
email: info@hatbarcelona.com
locale: en
keywords: barcelona maresme events eventos esdeveniments services servicios serveis bodas bodes weddings corporative corporativos corporatius catalunya cataluña
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.hatbarcelona.com" # the base hostname & protocol for your site
exclude: [Gemfile, Gemfile.lock, vendor]

locales:
  en: en_GB
  es: es_ES
  ca: ca_ES

# Build settings
markdown: kramdown

author:
  twitter: openfcsonline

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
